name: ci

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: rm -Rf vendor
      - uses: php-actions/composer@v6
      - run: ./vendor/bin/phpunit api.php