name: ci

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: rm -Rf vendor
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.3.8"
          version: 1
      - run: ./vendor/bin/phpunit